// lib/products.ts
export const templateData = [
  {
    id: 508811,
    slug: "e-commerce-template",
    name: "E-Commerce Template",
    description:
      "Modern e-commerce template built with Tailwind CSS. Fast, responsive, and perfect for launching your digital store.",
    demoUrl: "https://bloomtpl-ecommerce-template.vercel.app/",
    images: [
      "/images/templates/e-commerce-template/preview-1.png",
      "/images/templates/e-commerce-template/preview-2.png",
      "/images/templates/e-commerce-template/preview-3.png",
      "/images/templates/e-commerce-template/preview-4.png",
    ],
    openGraphImage: "/images/templates/e-commerce-template/og.png",
    category: "E-Commerce",
    pages: ["Home", "Shop", "Product", "Cart", "About", "Contact"],
    tech: ["Next.js 15 (App Router)", "Tailwind CSS 3"],
    extras: [
      "Built for conversion-focused storefronts",
      "Easy to customize with clean component structure",
      "Cart functionality with local storage",
      "Deployment-ready for Vercel",
    ],
  },
  {
    id: 509780,
    slug: "saas-dashboard-template",
    name: "SaaS Dashboard Template",
    description:
      "Modern SaaS dashboard template built with Next.js and Tailwind CSS. Clean, fast, and ideal for launching your next admin panel or internal tool.",
    demoUrl: "https://bloomtpl-dashboard-template.vercel.app/",
    images: [
      "/images/templates/saas-dashboard-template/preview-1.png",
      "/images/templates/saas-dashboard-template/preview-2.png",
      "/images/templates/saas-dashboard-template/preview-3.png",
      "/images/templates/saas-dashboard-template/preview-4.png",
    ],
    openGraphImage: "/images/templates/saas-dashboard-template/og.png",
    category: "Dashboard",
    tech: [
      "Next.js 15 (App Router)",
      "Tailwind CSS 3",
      "Lucide React",
      "Framer Motion",
      "Shadcn UI",
    ],
    pages: ["Home", "Users", "Statistics", "Settings"],
    extras: [
      "Modern dashboard layout with sidebar navigation",
      "User management with search and filtering",
      "Dark/Light mode toggle",
      "Animated charts and statistics",
      "Deployment-ready for Vercel",
    ],
  },
  {
    id: 509512,
    slug: "blog-template",
    name: "Blog Template",
    description:
      "Minimalist blog template built with Next.js and Tailwind CSS. Clean, fast, and perfect for launching your personal blog, journal, or editorial site.",
    demoUrl: "https://bloomtpl-blog-template.vercel.app/",
    images: [
      "/images/templates/blog-template/preview-1.png",
      "/images/templates/blog-template/preview-2.png",
      "/images/templates/blog-template/preview-3.png",
      "/images/templates/blog-template/preview-4.png",
    ],
    openGraphImage: "/images/templates/blog-template/og.png",
    category: "Blog",
    tech: ["Next.js 15 (App Router)", "Tailwind CSS 3", "Lucide React"],
    pages: ["Home", "Blog (Post)", "Author"],
    extras: [
      "Dynamic routing for posts and authors",
      "Dark mode support",
      "Category filtering via URL params",
      "Deployment-ready for Vercel",
    ],
  },
  {
    id: 529635,
    slug: "developer-portfolio-template",
    name: "Developer Portfolio Template",
    description:
      "A sleek and professional portfolio template built with Next.js 15 and Tailwind CSS. Perfect for developers, freelancers, and indie hackers who want to showcase their work, experience, and skills with style.",
    demoUrl: "https://bloomtpl-dev-portfolio-template.vercel.app/",
    images: [
      "/images/templates/dev-portfolio-template/preview-1.png",
      "/images/templates/dev-portfolio-template/preview-2.png",
      "/images/templates/dev-portfolio-template/preview-3.png",
      "/images/templates/dev-portfolio-template/preview-4.png",
    ],
    openGraphImage: "/images/templates/dev-portfolio-template/og.png",
    category: "Portfolio",
    tech: ["Next.js 15 (App Router)", "Tailwind CSS 3", "Lucide React"],
    pages: ["Home"],
    extras: [
      "Clean and minimal folder structure",
      "Dark/Light mode toggle with next-themes",
      "Fully responsive across devices",
      "SEO-friendly setup with metadata",
      "Deployment-ready for Vercel",
    ],
  },
  {
    id: 532956,
    slug: "restaurant-template",
    name: "Restaurant Template",
    description:
      "Modern restaurant website template built with Next.js and Tailwind CSS. Perfect for showcasing a menu, taking reservations, and attracting local food lovers.",
    demoUrl: "https://bloomtpl-restaurant-template.vercel.app/",
    images: [
      "/images/templates/restaurant-template/preview-1.png",
      "/images/templates/restaurant-template/preview-2.png",
      "/images/templates/restaurant-template/preview-3.png",
      "/images/templates/restaurant-template/preview-4.png",
      "/images/templates/restaurant-template/preview-5.png",
    ],
    openGraphImage: "/images/templates/restaurant-template/og.png",
    category: "Restaurant",
    tech: [
      "Next.js 15 (App Router)",
      "Tailwind CSS 3",
      "Framer Motion",
      "Lucide React",
    ],
    pages: ["Home"],
    extras: [
      "Gallery with lightbox image preview",
      "Auto-rotating testimonial carousel",
      "Deployment-ready for Vercel",
    ],
  },
  {
    id: 540440,
    slug: "saas-template",
    name: "SaaS Template",
    description:
      "A modern dark-mode SaaS UI template built with Next.js and Tailwind CSS. Clean, fast, responsive and ready to launch your own SaaS.",
    demoUrl: "https://bloomtpl-saas-template.vercel.app/",
    images: [
      "/images/templates/saas-template/preview-1.png",
      "/images/templates/saas-template/preview-2.png",
      "/images/templates/saas-template/preview-3.png",
      "/images/templates/saas-template/preview-4.png",
      "/images/templates/saas-template/preview-5.png",
    ],
    openGraphImage: "/images/templates/saas-template/og.png",
    category: "SaaS",
    tech: [
      "Next.js 15 (App Router)",
      "Tailwind CSS 3",
      "Framer Motion",
      "Lucide React",
    ],
    pages: [
      "Home",
      "Product",
      "Pricing",
      "Contact",
      "Resources",
      "Legal (Terms, Privacy)",
      "404",
    ],
    extras: [
      "Clean, modular components",
      "Dark mode UI",
      "SEO-ready metadata",
      "Animated sections (Hero, Pricing, FAQ)",
      "Deployment-ready for Vercel",
    ],
  },
  {
    id: 554503,
    slug: "coresaas-premium-saas-starter-kit-boilerplate",
    name: "CoreSaaS – Premium SaaS Starter Kit & Boilerplate",
    description:
      "Launch your SaaS faster with a complete starter kit: authentication, Stripe billing, admin dashboard, and user management – built with Next.js and Tailwind CSS.",
    demoUrl: "https://bloomtpl-coresaas-template.vercel.app/",
    images: [
      "/images/templates/coresaas-boilerplate/preview-1.png",
      "/images/templates/coresaas-boilerplate/preview-2.png",
      "/images/templates/coresaas-boilerplate/preview-3.png",
      "/images/templates/coresaas-boilerplate/preview-4.png",
      "/images/templates/coresaas-boilerplate/preview-5.png",
      "/images/templates/coresaas-boilerplate/preview-6.png",
    ],
    openGraphImage: "/images/templates/coresaas-boilerplate/og.png",
    category: "SaaS",
    tech: [
      "Next.js 15 (App Router)",
      "TypeScript",
      "Tailwind CSS 3",
      "shadcn/ui",
      "Framer Motion",
      "Lucide React",
      "Prisma",
      "PostgreSQL",
      "Stripe",
      "NextAuth.js",
    ],
    pages: [
      "Landing",
      "Dashboard",
      "Admin",
      "Sign In",
      "Contact",
      "403 Unauthorized",
      "404 Not Found",
      "Demo ( Admin / Dashboard )",
    ],
    extras: [
      "Email magic link authentication",
      "Stripe billing integration (monthly & yearly plans)",
      "Admin dashboard with user management",
      "Responsive and accessible UI",
      "Dark mode support",
      "Easy theme toggling",
      "Modern, animated landing page sections",
      "Ready-to-use contact and error pages",
      "Pre-built pricing, testimonials, and features sections",
      "Developer-friendly codebase with ESLint and TypeScript",
      "Prisma ORM with PostgreSQL support",
    ],
  },
  {
    id: 562201,
    slug: "blogstarter-premium-blog-starter-kit",
    name: "BlogStarter – Premium Blog Starter Kit",
    description:
      "Kickstart your modern blog with BloomTPL BlogStarter, a feature-rich Next.js starter kit powered by Sanity.io and styled with Tailwind CSS. Fast, customizable, and production-ready.",
    demoUrl: "https://bloomtpl-blogstarter-starter-kit.vercel.app/",
    images: [
      "/images/templates/blogstarter-starterkit/preview-1.png",
      "/images/templates/blogstarter-starterkit/preview-2.png",
      "/images/templates/blogstarter-starterkit/preview-3.png",
      "/images/templates/blogstarter-starterkit/preview-4.png",
    ],
    openGraphImage: "/images/templates/blogstarter-starterkit/og.png",
    category: "Blog",
    tech: [
      "Next.js 15 (App Router)",
      "TypeScript",
      "Tailwind CSS",
      "shadcn/ui",
      "Lucide React",
      "Sanity.io (Headless CMS)",
    ],
    pages: ["Landing (Latest Posts)", "Category", "Author", "Blog Post"],
    extras: [
      "Sanity CMS integration",
      "Responsive and accessible UI",
      "Dark mode support",
      "Easy theme toggling",
      "Pre-built author and category pages",
      "Developer-friendly codebase with ESLint and TypeScript",
    ],
  },
];

export function getTemplateBySlug(slug: string) {
  return templateData.find((tpl) => tpl.slug === slug);
}
